### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by arghasen10** [imec-idlab/NB-IoT#1]
No code available. How did the paper get published in WNGW'19? @ashishsultania

**Comment by ashishsultania** [comment]
Hello @arghasen10 , you should check the README first. It is clearly mentioned that "This is the repository from Imec research group on development of NB-IoT features on ns-3 network simulator. It consists of two branches namely energy_evaluation and repetition_coverage."
![Capture](https://user-images.githubusercontent.com/13823696/149535922-71425326-146c-4fa7-852e-8f7c6aacdcf8.JPG)

**Comment by arghasen10** [comment]
Right. My bad.
